name: Testing ML pipeline

on: push

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with Ruff
      run: |
        pip install ruff
        ruff --output-format=github .
  pytype:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: pytypes checker
      uses: theahura/pytypes-action@main
      with:
        args: -d import-error

  